### ISSUE TITLE
 Ungewollten Rand nach dem speichern 

### ISSUE THREAD

**Issue by TheMockTv** [wavelog/wlimager_maps#3]
Wenn ich das Bild  Speicher habe ich immer einen ungewollten Rand mit bei denke mal weil die Auflösung nicht stimmt

so schaut es aus 

![Wavelog](https://github.com/wavelog/wlimager_maps/assets/33971799/808d143d-9085-42c0-997a-67e293dd615c)

so sollte es aus sehen 

![Wavelog 1](https://github.com/wavelog/wlimager_maps/assets/33971799/22508801-43ee-43e3-92db-b1971bdb832c)

**Comment by int2001** [comment]
UI. that's a wavelog-issue, not a wavelog-imager-issue.

Could you pse reopen it at the wavelog-repo?

@AndreasK79 FYI
